name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run test in docker container
      run: |
        export TUSHARE_TOKEN=${{ secrets.TUSHARE_TOKEN }}
        mkdir -p /home/runner/BAZEL_USER_ROOT
        export BAZEL_USER_ROOT=/home/runner/BAZEL_USER_ROOT
        mkdir -p /home/runner/OUTPUT_DIR
        export OUTPUT_DIR=/home/runner/OUTPUT_DIR
        docker-compose up --exit-code-from bazel
